apiVersion: apps/v1
kind: Deployment
metadata:
  name: mythical-mysfits-eks
  labels:
    app: mythical-mysfits-eks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mythical-mysfits-eks
  template:
    metadata:
      labels:
        app: mythical-mysfits-eks
    spec:
      containers:
        - name: mythical-mysfits-eks
          image: 521538833543.dkr.ecr.us-west-2.amazonaws.com/mythic-mono-1mlmxg9hhf7v3:nolike
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DDB_TABLE_NAME
              value: Table-mythical-mysfits-core
            - name: AWS_DEFAULT_REGION
              value: us-west-2
---
apiVersion: v1
kind: Service
metadata:
  name: mythical-mysfits-eks
spec:
  type: NodePort
  selector:
    app: mythical-mysfits-eks
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80